[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = "/pawcare"
  BASE_PATH = "/pawcare"

[[redirects]]
  from = "/pawcare/*"
  to = "/pawcare/index.html"
  status = 200
